name: cd
on:
  push:
    branches:
      - teleport
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: setup python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.15"
          # TODO: remove when 3.15 stable is released
          allow-prereleases: true
      - name: install
        run: pip install .[dev]
      - name: build docker image
        run: docker build . --tag gravitational/aws-quota-checker:test
      - name: build helm chart
        working-directory: helm
        run: helm package . --version "1.2.3-dev" --app-version "4.5.6-dev"

  build_and_push_artifacts:
    runs-on: ubuntu-latest
    needs: [test]
    name: Build and push artifacts
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        id: login-ghcr
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare docker labels and tags
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
          # Enable sha tag on branch push events and workflow dispatches.
          # Enable semver tags on tag push events, but don't overwrite major/minor tags for prereleases.
          tags: |
            type=sha,prefix={{branch}}-,suffix=-{{date 'YYYYMMDDTHHmmss'}},format=short,enable=${{ startsWith(github.ref, 'refs/heads/') }}
            type=semver,pattern={{major}},enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
            type=semver,pattern={{version}},enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}

      - name: Build the Docker image and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/amd64
            linux/arm64

      - name: Build and publish the Helm chart
        working-directory: helm
        env:
          EVENT_TYPE: ${{ (github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') && 'tag' ) || 'commit' ) || 'dispatch'}}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_VERSION: ${{ steps.meta.outputs.version }}
        run: |
          # Determine chart version to set
          case "${EVENT_TYPE}" in
            tag)
              CHART_VERSION="${GITHUB_REF_NAME}"
              ;;
            commit)
              ;&
            dispatch)
              CHART_VERSION="$(git describe --tags --dirty --long --match "v[[:digit:]]*.[[:digit:]]*.[[:digit:]]*")"
              ;;
            *)
              echo "Unknown event type '${EVENT_TYPE}', workflow bug?" >&2
              exit 1
              ;;
          esac

          # Trim `v` prefix if exists
          CHART_VERSION=${CHART_VERSION#v}
          IMAGE_VERSION=${IMAGE_VERSION#v}

          # Build/package the chart
          echo "Setting chart version to ${CHART_VERSION} and image version to ${IMAGE_VERSION}"
          helm package . --version "${CHART_VERSION}" --app-version "${IMAGE_VERSION}"
          ARTIFACT_NAME=$(find . -name '*.tgz' -exec basename {} \; | head -n 1)

          # Publish the chart
          printf '%s' "${GHCR_TOKEN}" | helm registry login ghcr.io \
            --username "${GITHUB_ACTOR}" \
            --password-stdin
          CHART_REGISTRY="oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"
          helm push "$ARTIFACT_NAME" "${CHART_REGISTRY}"
