on:
  workflow_dispatch:
    - eip_count_current
  pull_request:
    branches:
      - teleport
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: setup python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.15"
          # TODO: remove when 3.15 stable is released
          allow-prereleases: true
      - name: install
        run: pip install .[dev]
      - name: build docker image
        run: docker build . --tag gravitational/aws-quota-checker:test
      - name: build helm chart
        working-directory: helm
        run: helm package .
