name: Dependency Review

on:
  workflow_dispatch:
  pull_request:

jobs:
  dependency-review:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    uses: gravitational/shared-workflows/.github/workflows/dependency-review.yaml@main
    permissions:
      contents: read
    with:
      allow-additional-licenses: >
        Apache-2.0 AND MIT AND MPL-2.0
